# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'ComicsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ComicsApp
  pod 'SDWebImage', '~> 5.21.0'


  target 'ComicsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ComicsAppUITests' do
    # Pods for testing
  end

end
